"""
Content Hints Models for Director Agent v4.0

Defines the data structures for content analysis and service routing.
These hints help determine which service (Text, Analytics, Diagram, Illustrator)
should handle a given slide's content generation.
"""

from typing import List, Optional
from pydantic import BaseModel, Field
from enum import Enum


class PatternType(str, Enum):
    """Types of content patterns detected in slides."""
    TIME_SERIES = "time_series"         # Data over time (trends, history)
    COMPARISON = "comparison"           # Side-by-side comparisons
    COMPOSITION = "composition"         # Parts of a whole (pie, breakdown)
    HIERARCHY = "hierarchy"             # Tree, org chart, levels
    FLOW = "flow"                       # Process, workflow, sequence
    METRICS = "metrics"                 # KPIs, numbers, statistics
    MATRIX = "matrix"                   # 2D grid (SWOT, prioritization)
    NARRATIVE = "narrative"             # Text-heavy, storytelling
    MIXED = "mixed"                     # Multiple patterns detected


class SuggestedService(str, Enum):
    """Services that can handle content generation."""
    TEXT = "text"                       # Text Service (34 variants + 12 hero + 12 I-series)
    ANALYTICS = "analytics"             # Analytics Service (charts, data viz)
    DIAGRAM = "diagram"                 # Diagram Service (Mermaid, SVG, Python)
    ILLUSTRATOR = "illustrator"         # Illustrator Service (pyramids, funnels)


class ContentHints(BaseModel):
    """
    Content analysis hints for service routing.

    Generated by ContentAnalyzer from slide content (title, topics).
    Used by service coordination clients to determine best routing.
    """
    # Boolean flags for content characteristics
    has_numbers: bool = Field(
        default=False,
        description="True if content contains numeric values (percentages, revenue, counts)"
    )
    is_comparison: bool = Field(
        default=False,
        description="True if content compares items (vs, compare, pros/cons)"
    )
    is_time_based: bool = Field(
        default=False,
        description="True if content has temporal elements (Q1, 2024, timeline, history)"
    )
    is_hierarchical: bool = Field(
        default=False,
        description="True if content has hierarchy (org chart, levels, tiers)"
    )
    is_process_flow: bool = Field(
        default=False,
        description="True if content describes a process or workflow"
    )
    is_sequential: bool = Field(
        default=False,
        description="True if content has ordered steps (1-2-3, first-then-finally)"
    )

    # Extracted data
    detected_keywords: List[str] = Field(
        default_factory=list,
        description="Keywords detected that inform service routing"
    )
    pattern_type: Optional[PatternType] = Field(
        default=None,
        description="Primary content pattern detected"
    )

    # Numeric analysis
    numeric_density: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
        description="Ratio of numeric content (0-1, higher = more numbers)"
    )

    # Content structure
    topic_count: int = Field(
        default=0,
        ge=0,
        description="Number of topics/points in the slide"
    )

    # I-series recommendations
    # v4.8: Unified Variant System - suggested_iseries now contains full Gold Standard
    # variant_id (e.g., "sequential_3col_i1") instead of just layout ID (I1/I2/I3/I4)
    needs_image: bool = Field(
        default=False,
        description="True if content would benefit from I-series (image+text) layout. "
                    "v4.8: Use is_iseries_variant(variant_id) for detection."
    )
    suggested_iseries: Optional[str] = Field(
        default=None,
        description="v4.8: Full Gold Standard I-series variant_id (e.g., 'sequential_3col_i1'). "
                    "Encodes both content template and image position."
    )

    # Service routing
    suggested_service: Optional[SuggestedService] = Field(
        default=None,
        description="Recommended service based on content analysis"
    )
    service_confidence: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
        description="Confidence in service recommendation (0-1)"
    )


class CanHandleRequest(BaseModel):
    """
    Request body for /can-handle endpoints on coordination services.

    Matches Text Service v1.2 /v1.2/can-handle request format.
    """
    slide_content: dict = Field(
        ...,
        description="Slide content with title, topics, topic_count"
    )
    content_hints: ContentHints = Field(
        ...,
        description="Content analysis hints"
    )
    available_space: dict = Field(
        ...,
        description="Available space with width, height, layout_id, optional sub_zones"
    )


class CanHandleResponse(BaseModel):
    """
    Response from /can-handle endpoints on coordination services.

    Matches Text Service v1.2 /v1.2/can-handle response format.
    """
    can_handle: bool = Field(
        ...,
        description="Whether the service can handle this content"
    )
    confidence: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Confidence score (0-1)"
    )
    reason: str = Field(
        ...,
        description="Explanation of the confidence score"
    )
    suggested_approach: Optional[str] = Field(
        default=None,
        description="Suggested approach/variant if can_handle is True"
    )
    space_utilization: Optional[dict] = Field(
        default=None,
        description="Space utilization details (fits_well, estimated_fill_percent)"
    )


class VariantRecommendation(BaseModel):
    """
    A single variant recommendation from /recommend-variant.
    """
    variant_id: str = Field(
        ...,
        description="The variant identifier"
    )
    confidence: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Confidence score for this variant"
    )
    reason: str = Field(
        ...,
        description="Why this variant is recommended"
    )
    requires_space: Optional[dict] = Field(
        default=None,
        description="Minimum space required (width, height)"
    )


class RecommendVariantResponse(BaseModel):
    """
    Response from /recommend-variant endpoints.

    Matches Text Service v1.2 /v1.2/recommend-variant response format.
    """
    recommended_variants: List[VariantRecommendation] = Field(
        default_factory=list,
        description="Ranked list of recommended variants"
    )
    not_recommended: Optional[List[dict]] = Field(
        default=None,
        description="Variants that were considered but not recommended"
    )
