"""
Content Generation Models - v3.1 / v4.2
=======================================

Data models for Stage 6 (Content Generation).
v3.1 scope: TEXT SERVICE ONLY (no images, charts, diagrams)
v4.2 scope: UniversalServiceResponse for multi-service content generation
"""

from typing import Dict, List, Optional, Any, Union
from pydantic import BaseModel, Field
from datetime import datetime
from .agents import Slide, PresentationStrawman


# ========== v4.2: Stage 6 - Universal Service Response ==========

class UniversalServiceResponse(BaseModel):
    """
    Universal response contract for all content generation services.

    v4.2: Stage 6 - All services (Text, Analytics, Illustrator, Diagram) return
    content in this unified format. Director only adds footer/logo.

    Format:
    - title_html: HTML-enriched title (e.g., "<h2 class='slide-title'>...</h2>")
    - subtitle_html: HTML-enriched subtitle (e.g., "<p class='slide-subtitle'>...</p>")
    - content_html: Main content HTML or structured element dict
    """
    success: bool = Field(..., description="Whether generation was successful")

    # HTML-enriched title and subtitle (generated by services)
    title_html: Optional[str] = Field(
        None,
        description="HTML-enriched title, e.g., '<h2 class=\"slide-title\">Title</h2>'"
    )
    subtitle_html: Optional[str] = Field(
        None,
        description="HTML-enriched subtitle, e.g., '<p class=\"slide-subtitle\">Subtitle</p>'"
    )

    # Main content (HTML string or structured dict for complex layouts)
    content_html: Union[str, Dict[str, Any]] = Field(
        "",
        description="Main slide content - HTML string or structured element dict"
    )

    # Service metadata
    metadata: Dict[str, Any] = Field(
        default_factory=dict,
        description="Service-specific metadata (variant_id, generation_time, etc.)"
    )

    # Error handling
    error: Optional[str] = Field(None, description="Error message if success=False")

    @property
    def has_title(self) -> bool:
        """Check if title was generated."""
        return bool(self.title_html)

    @property
    def has_subtitle(self) -> bool:
        """Check if subtitle was generated."""
        return bool(self.subtitle_html)

    def to_assembled_html(self) -> str:
        """
        Assemble complete slide HTML from components.

        Returns:
            Combined HTML with title + subtitle + content
        """
        parts = []
        if self.title_html:
            parts.append(self.title_html)
        if self.subtitle_html:
            parts.append(self.subtitle_html)
        if self.content_html:
            if isinstance(self.content_html, dict):
                # For structured content, we'll need layout-specific assembly
                # This is a fallback - normally the layout renderer handles this
                parts.append(f"<!-- structured: {list(self.content_html.keys())} -->")
            else:
                parts.append(self.content_html)
        return "\n".join(parts)


class TitleSubtitleResponse(BaseModel):
    """
    Response from Text Service title/subtitle endpoints.

    Used when generating titles for non-Text-Service slides
    (Analytics, Illustrator, Diagram).
    """
    title_html: Optional[str] = Field(None, description="Generated title HTML")
    subtitle_html: Optional[str] = Field(None, description="Generated subtitle HTML")
    metadata: Dict[str, Any] = Field(default_factory=dict)


# ========== v3.1: Original Content Models ==========


class GeneratedText(BaseModel):
    """
    Generated text content from Text Service.

    v3.1: Simple structure - just content and metadata.
    v1.1: Enhanced to support both string (legacy) and dict (structured) content.
    """
    content: Union[str, Dict[str, Any]] = Field(
        description="Generated content - string (HTML/text for v1.0) or dict (structured for v1.1)"
    )
    metadata: Dict[str, Any] = Field(
        default_factory=dict,
        description="Optional metadata like word_count, generation_time_ms, model_used"
    )


class EnrichedSlide(BaseModel):
    """
    A slide with generated text content attached.

    v3.1 scope: TEXT ONLY
    - original_slide: The full input Slide from strawman
    - generated_text: Generated text content (or None if failed)
    - has_text_failure: Flag indicating if text generation failed
    """
    original_slide: Slide = Field(
        description="The full input slide from strawman"
    )
    slide_id: str = Field(
        description="Slide identifier for easy reference"
    )
    generated_text: Optional[GeneratedText] = Field(
        default=None,
        description="Generated text content (None if generation failed)"
    )
    has_text_failure: bool = Field(
        default=False,
        description="True if text generation failed for this slide"
    )


class EnrichedPresentationStrawman(BaseModel):
    """
    Presentation strawman with generated text content.

    v3.1 scope: TEXT SERVICE ONLY
    - original_strawman: The full input PresentationStrawman from Stage 5
    - enriched_slides: Array of EnrichedSlide with text content
    - generation_metadata: Stats about the text generation process
    """
    original_strawman: PresentationStrawman = Field(
        description="The full input strawman from Director Stage 5"
    )
    enriched_slides: List[EnrichedSlide] = Field(
        description="Slides with generated text content"
    )
    generation_metadata: Dict[str, Any] = Field(
        default_factory=dict,
        description="Metadata about generation process",
        example={
            "total_slides": 10,
            "successful_slides": 9,
            "failed_slides": 1,
            "generation_time_seconds": 45,
            "timestamp": "2025-10-20T12:34:56Z",
            "service_used": "text_service_v1.0"
        }
    )

    @property
    def success_rate(self) -> float:
        """Calculate success rate of text generation."""
        metadata = self.generation_metadata
        total = metadata.get("total_slides", 0)
        if total == 0:
            return 0.0
        successful = metadata.get("successful_slides", 0)
        return (successful / total) * 100

    @property
    def has_failures(self) -> bool:
        """Check if any slides had text generation failures."""
        return any(slide.has_text_failure for slide in self.enriched_slides)
