"""
Conversation Tools for Director Agent v4.0

Low-cost internal tools for conversational interactions:
- RespondTool: Generate conversational responses
- AskQuestionsTool: Generate clarifying questions
- ProposePlanTool: Generate presentation plan proposals
"""

import logging
from typing import Dict, Any, Optional, List

from .base_tool import BaseTool, ToolDefinition, ToolResult, CostTier

logger = logging.getLogger(__name__)


class RespondTool(BaseTool):
    """
    Tool for generating conversational responses.

    Used for greetings, acknowledgments, clarifications, and general
    conversation that doesn't require external service calls.
    """

    def get_definition(self) -> ToolDefinition:
        return ToolDefinition(
            tool_id="conversation.respond",
            display_name="Respond Conversationally",
            description=(
                "Generate a natural conversational response to the user. "
                "Use for greetings, acknowledgments, clarifications, and "
                "general conversation that doesn't require tools."
            ),
            cost_tier=CostTier.LOW,
            requires_context=[],
            requires_approval=False,
            input_schema={
                "type": "object",
                "required": ["intent"],
                "properties": {
                    "intent": {
                        "type": "string",
                        "description": "The intent of the response"
                    },
                    "tone": {
                        "type": "string",
                        "enum": ["professional", "friendly", "encouraging"],
                        "default": "professional"
                    },
                    "message": {
                        "type": "string",
                        "description": "The response message content"
                    }
                }
            },
            output_schema={
                "type": "object",
                "properties": {
                    "response_text": {"type": "string"}
                }
            }
        )

    async def execute(
        self,
        parameters: Dict[str, Any],
        context: Optional[Dict[str, Any]] = None
    ) -> ToolResult:
        """
        Execute the respond tool.

        This is primarily a pass-through - the actual response content
        is generated by the Decision Engine and passed in parameters.
        """
        intent = parameters.get('intent', 'response')
        message = parameters.get('message', '')
        tone = parameters.get('tone', 'professional')

        logger.debug(f"RespondTool: intent={intent}, tone={tone}")

        return ToolResult(
            success=True,
            data={
                "response_text": message,
                "intent": intent,
                "tone": tone
            },
            tool_id=self.tool_id
        )


class AskQuestionsTool(BaseTool):
    """
    Tool for generating clarifying questions.

    Used when more information is needed to create a good presentation.
    Generates 3-5 targeted questions based on what's missing.
    """

    def get_definition(self) -> ToolDefinition:
        return ToolDefinition(
            tool_id="conversation.ask_questions",
            display_name="Ask Clarifying Questions",
            description=(
                "Generate intelligent clarifying questions to gather "
                "information needed for presentation creation. Use when "
                "topic is vague or missing critical details like audience, "
                "duration, or purpose."
            ),
            cost_tier=CostTier.LOW,
            requires_context=[],
            requires_approval=False,
            input_schema={
                "type": "object",
                "required": ["topic"],
                "properties": {
                    "topic": {
                        "type": "string",
                        "description": "The user's stated topic"
                    },
                    "missing_info": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "Categories of missing information"
                    },
                    "context": {
                        "type": "string",
                        "description": "Additional context from conversation"
                    },
                    "questions": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "Pre-generated questions to use"
                    }
                }
            },
            output_schema={
                "type": "object",
                "properties": {
                    "questions": {
                        "type": "array",
                        "items": {"type": "string"},
                        "minItems": 3,
                        "maxItems": 5
                    },
                    "intro_text": {"type": "string"}
                }
            }
        )

    async def execute(
        self,
        parameters: Dict[str, Any],
        context: Optional[Dict[str, Any]] = None
    ) -> ToolResult:
        """
        Execute the ask questions tool.

        If questions are provided in parameters, use those.
        Otherwise, generate default questions based on missing info.
        """
        topic = parameters.get('topic', '')
        missing_info = parameters.get('missing_info', [])
        questions = parameters.get('questions', [])

        # If questions provided, use them
        if questions:
            return ToolResult(
                success=True,
                data={
                    "questions": questions[:5],  # Max 5
                    "intro_text": f"To create the best presentation about '{topic}', I have a few questions:"
                },
                tool_id=self.tool_id
            )

        # Generate default questions based on missing info
        default_questions = self._generate_default_questions(topic, missing_info)

        return ToolResult(
            success=True,
            data={
                "questions": default_questions,
                "intro_text": f"To create the best presentation about '{topic}', I have a few questions:"
            },
            tool_id=self.tool_id
        )

    def _generate_default_questions(
        self,
        topic: str,
        missing_info: List[str]
    ) -> List[str]:
        """Generate default clarifying questions."""
        question_templates = {
            "audience": "Who is the target audience for this presentation? (e.g., executives, team members, clients, students)",
            "duration": "How long should the presentation be? (e.g., 5 minutes, 15 minutes, 30 minutes)",
            "purpose": "What is the main goal of the presentation? (e.g., inform, persuade, teach, report)",
            "tone": "What tone or style would you prefer? (e.g., professional, casual, inspirational)",
            "depth": "How detailed should the content be? (e.g., high-level overview, deep dive)",
            "key_message": "What is the single most important takeaway for your audience?",
            "constraints": "Are there any specific requirements or constraints I should know about?"
        }

        questions = []

        # Add questions for explicitly missing info
        for info in missing_info:
            if info in question_templates:
                questions.append(question_templates[info])

        # If we have fewer than 3 questions, add defaults
        default_order = ["audience", "purpose", "duration", "tone", "key_message"]
        for key in default_order:
            if len(questions) >= 5:
                break
            template = question_templates[key]
            if template not in questions:
                questions.append(template)

        return questions[:5]


class ProposePlanTool(BaseTool):
    """
    Tool for generating presentation plan proposals.

    Creates a high-level plan with proposed slide count and key assumptions
    based on gathered context.
    """

    def get_definition(self) -> ToolDefinition:
        return ToolDefinition(
            tool_id="conversation.propose_plan",
            display_name="Propose Presentation Plan",
            description=(
                "Generate a high-level presentation plan with proposed "
                "slide count and key assumptions. Use after gathering "
                "enough context about the presentation needs."
            ),
            cost_tier=CostTier.LOW,
            requires_context=["initial_request"],
            requires_approval=False,
            input_schema={
                "type": "object",
                "required": ["topic"],
                "properties": {
                    "topic": {
                        "type": "string",
                        "description": "Presentation topic"
                    },
                    "audience": {
                        "type": "string",
                        "description": "Target audience"
                    },
                    "purpose": {
                        "type": "string",
                        "description": "Goal of the presentation"
                    },
                    "duration": {
                        "type": "integer",
                        "description": "Expected duration in minutes"
                    },
                    "tone": {
                        "type": "string",
                        "description": "Desired tone/style"
                    },
                    "summary": {
                        "type": "string",
                        "description": "Pre-generated summary"
                    },
                    "proposed_slide_count": {
                        "type": "integer",
                        "description": "Pre-determined slide count"
                    },
                    "key_assumptions": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "Pre-generated assumptions"
                    }
                }
            },
            output_schema={
                "type": "object",
                "properties": {
                    "summary": {"type": "string"},
                    "proposed_slide_count": {"type": "integer"},
                    "key_assumptions": {
                        "type": "array",
                        "items": {"type": "string"}
                    },
                    "structure_overview": {"type": "string"}
                }
            }
        )

    async def execute(
        self,
        parameters: Dict[str, Any],
        context: Optional[Dict[str, Any]] = None
    ) -> ToolResult:
        """
        Execute the propose plan tool.

        If plan details provided in parameters, use those.
        Otherwise, generate a default plan based on context.
        """
        topic = parameters.get('topic', '')
        audience = parameters.get('audience', 'general')
        purpose = parameters.get('purpose', 'inform')
        duration = parameters.get('duration', 15)

        # Use provided values or generate defaults
        summary = parameters.get('summary') or self._generate_summary(
            topic, audience, purpose
        )
        slide_count = parameters.get('proposed_slide_count') or self._estimate_slides(
            duration
        )
        assumptions = parameters.get('key_assumptions') or self._generate_assumptions(
            topic, audience, purpose, duration
        )

        structure = self._generate_structure_overview(slide_count)

        return ToolResult(
            success=True,
            data={
                "summary": summary,
                "proposed_slide_count": slide_count,
                "key_assumptions": assumptions,
                "structure_overview": structure
            },
            tool_id=self.tool_id
        )

    def _generate_summary(
        self,
        topic: str,
        audience: str,
        purpose: str
    ) -> str:
        """Generate a summary of the presentation plan."""
        return (
            f"A presentation about '{topic}' for {audience}, "
            f"designed to {purpose}."
        )

    def _estimate_slides(self, duration: int) -> int:
        """Estimate slide count based on duration."""
        # Roughly 2 minutes per slide for a paced presentation
        base_slides = max(2, duration // 2)
        # Add title and closing
        return min(30, max(5, base_slides + 2))

    def _generate_assumptions(
        self,
        topic: str,
        audience: str,
        purpose: str,
        duration: int
    ) -> List[str]:
        """Generate key assumptions for the plan."""
        assumptions = [
            f"Target audience: {audience}",
            f"Presentation goal: {purpose}",
            f"Estimated duration: {duration} minutes"
        ]

        if audience.lower() in ['executives', 'board', 'leadership']:
            assumptions.append("Will include executive summary upfront")

        return assumptions

    def _generate_structure_overview(self, slide_count: int) -> str:
        """Generate a structure overview."""
        if slide_count <= 5:
            return "Compact structure: Title, 3-4 content slides, Closing"
        elif slide_count <= 10:
            return "Standard structure: Title, Introduction, Main sections, Conclusion, Closing"
        else:
            return "Extended structure: Title, Executive Summary, Multiple sections with dividers, Conclusion, Closing"
